#!/bin/bash
# Find the current encoding of the file
encoding=$(file -i "$1" | sed "s/.*charset=\(.*\)$/\1/")

echo $encoding
case $encoding in
	utf-16le)
		recode UTF-16..UTF8 "$1"
		;;
	utf-8)
		;;
	*)
		recode GBK..UTF8 "$1"
		;;
esac
