

//********************************************* 三对0********************
#undef my_m_MT_R_3pawn  
#undef my_m_MT_R_1pao2pawn  
//********************************************* 三对1********************
#undef my_m_MT_R_1che_1pao_1pawn_B_1che  
#undef my_m_MT_R_1che_1ma_1pawn_B_1che  
#undef my_m_MT_R_1CHE_2PAWN_B_1CHE  
#undef my_m_MT_R_1che_2pawn_B_1pao  
#undef my_m_MT_R_1che_2pawn_B_1ma  
#undef my_m_MT_R_1che_2pawn_B_1pawn  
#undef my_m_MT_R_2pao_1ma_B_1che  
#undef my_m_MT_R_1pao_2ma_B_1che  
#undef my_m_MT_R_2pao_1pawn_B_1che  
#undef my_m_MT_R_2pao_1pawn_B_1pao  
#undef my_m_MT_R_2pao_1pawn_B_1ma  
#undef my_m_MT_R_2pao_1pawn_B_1pawn  
#undef my_m_MT_R_1pao1ma_1pawn_B_1che  
#undef my_m_MT_R_1pao1ma_1pawn_B_1pao  
#undef my_m_MT_R_1pao1ma_1pawn_B_1ma  
#undef my_m_MT_R_1pao1ma_1pawn_B_1pawn  
#undef my_m_MT_R_2ma_1pawn_B_1che  
#undef my_m_MT_R_2ma_1pawn_B_1pao  
#undef my_m_MT_R_2ma_1pawn_B_1ma  
#undef my_m_MT_R_2ma_1pawn_B_1pawn  
#undef my_m_MT_R_1pao2pawn_B_1che  
#undef my_m_MT_R_1PAO2PAWN_B_1PAO  
#undef my_m_MT_R_1PAO2PAWN_B_1MA  
#undef my_m_MT_R_1pao2pawn_B_1pawn  
#undef my_m_MT_R_1ma2pawn_B_1che  
#undef my_m_MT_R_1ma2pawn_B_1pao  
#undef my_m_MT_R_1ma2pawn_B_1ma  
#undef my_m_MT_R_1ma2pawn_B_1pawn  
#undef my_m_MT_R_3PAWN_B_1CHE  
#undef my_m_MT_R_3pawn_B_1pao  
#undef my_m_MT_R_3pawn_B_1ma  
#undef my_m_MT_R_3pawn_B_1pawn  
//********************************************* 三对2********************
#undef my_m_MT_R_2che1ma_B_2che               
#undef my_m_MT_R_2che1pao_B_2che      
#undef my_m_MT_R_2che1pawn_B_2che  
#undef my_m_MT_R_2che1pawn_B_1che1pao  
#undef my_m_MT_R_2che1pawn_B_1che1ma 
#undef my_m_MT_R_1che2pao_B_1che1pao  
#undef my_m_MT_R_1che2pao_B_2che  
#undef my_m_MT_R_1che1pao1ma_B_2che  
#undef my_m_MT_R_1che1pao1ma_B_1che1pao  
#undef my_m_MT_R_1che1pao1ma_B_1che1ma  
#undef my_m_MT_R_1che1pao1ma_B_1che1pawn 
#undef my_m_MT_R_1che2pao_B_1che1ma  
#undef my_m_MT_R_1che1pao1pawn_B_2che  
#undef my_m_MT_R_1che1pao1pawn_B_1che1pao  
#undef my_m_MT_R_1che1pao1pawn_B_1che1ma  
#undef my_m_MT_R_1che1pao1pawn_B_1che1pawn  
#undef my_m_MT_R_1che1ma1pawn_B_2che  
#undef my_m_MT_R_1che1ma1pawn_B_1che1pao  
#undef my_m_MT_R_1che1ma1pawn_B_1che1ma  
#undef my_m_MT_R_1che1ma1pawn_B_1che1pawn  
#undef my_m_MT_R_1che2ma_B_2che  
#undef my_m_MT_R_1che2ma_B_1che1pao  
#undef my_m_MT_R_1che2ma_B_1che1ma  
#undef my_m_MT_R_1che2pawn_B_2che        
#undef my_m_MT_R_1CHE2PAWN_B_1CHE1PAO  
#undef my_m_MT_R_1che2pawn_B_2pao  
#undef my_m_MT_R_1che2pawn_B_1pao1ma  
#undef my_m_MT_R_1che2pawn_B_2ma  
#undef my_m_MT_R_1che2pawn_B_1pao1pawn  
#undef my_m_MT_R_1che2pawn_B_1ma1pawn  
#undef my_m_MT_R_1che2pawn_B_2pawn  
#undef my_m_MT_R_1che2pawn_B_1che1ma  
#undef my_m_MT_R_1che2pawn_B_1che1pawn  
#undef my_m_MT_R_2pao1ma_B_1che1pao  
#undef my_m_MT_R_2pao1ma_B_2che           
#undef my_m_MT_R_2pao1ma_B_1che1ma  
#undef my_m_MT_R_1pao2ma_B_1che1pao  
#undef my_m_MT_R_1pao2ma_B_1che1ma  
#undef my_m_MT_R_2pao_1ma_B_1che1pawn  
#undef my_m_MT_R_1pao_2ma_B_1che1pawn  
#undef my_m_MT_R_2pao1pawn_B_1che1pao  
#undef my_m_MT_R_2pao1pawn_B_1che1ma  
#undef my_m_MT_R_2pao1pawn_B_1che1pawn  
#undef my_m_MT_R_2pao1pawn_B_2pao  
#undef my_m_MT_R_2pao1pawn_B_1pao1ma  
#undef my_m_MT_R_2pao1pawn_B_2ma 
#undef my_m_MT_R_2pao1pawn_B_1pao1pawn 
#undef my_m_MT_R_2pao1pawn_B_1ma1pawn  
#undef my_m_MT_R_1ma1pao1pawn_B_1che1pao 
#undef my_m_MT_R_1ma1pao1pawn_B_1che1ma      
#undef my_m_MT_R_1ma1pao1pawn_B_1che1pawn  
#undef my_m_MT_R_1ma1pao1pawn_B_2pao  
#undef my_m_MT_R_1ma1pao1pawn_B_2ma  
#undef my_m_MT_R_1ma1pao1pawn_B_1ma1pao  	
#undef my_m_MT_R_1ma1pao1pawn_B_1pao1pawn  
#undef my_m_MT_R_1ma1pao1pawn_B_1ma1pawn  
#undef my_m_MT_R_2ma1pawn_B_1che1ma  
#undef my_m_MT_R_2ma1pawn_B_1che1pawn  
#undef my_m_MT_R_2ma1pawn_B_2pao  
#undef my_m_MT_R_2ma1pawn_B_1ma1pao  
#undef my_m_MT_R_2ma1pawn_B_2ma  
#undef my_m_MT_R_2ma1pawn_B_1pao1pawn  
#undef my_m_MT_R_2ma1pawn_B_1ma1pawn  
#undef my_m_MT_R_1pao2pawn_B_1che1pawn  
#undef my_m_MT_R_1pao2pawn_B_2pao  
#undef my_m_MT_R_1pao2pawn_B_1pao1ma  
#undef my_m_MT_R_1pao2pawn_B_2ma  
#undef my_m_MT_R_1pao2pawn_B_1pao1pawn  
#undef my_m_MT_R_1pao2pawn_B_1ma1pawn  
#undef my_m_MT_R_1pao2pawn_B_2pawn  
#undef my_m_MT_R_1ma2pawn_B_1che1pawn	
#undef my_m_MT_R_1ma2pawn_B_2pao  
#undef my_m_MT_R_1ma2pawn_B_1pao1ma  
#undef my_m_MT_R_1ma2pawn_B_2ma  
#undef my_m_MT_R_1ma2pawn_B_1pao1pawn  
#undef my_m_MT_R_1ma2pawn_B_1ma1pawn  
#undef my_m_MT_R_1ma2pawn_B_2pawn  
#undef my_m_MT_R_3pawn_B_1che1pawn      
#undef my_m_MT_R_3pawn_B_1pao1pawn      
#undef my_m_MT_R_3pawn_B_1ma1pawn       
#undef my_m_MT_R_3pawn_B_2pawn  
//********************************************* 3 对 3********************
#undef my_m_MT_R_2che1pao_B_2che1pawn 
#undef my_m_MT_R_2che1ma_B_2che1pawn          
#undef my_m_MT_R_2che1pawn_B_1che2pao  
#undef my_m_MT_R_2che1pawn_B_1che1pao1ma  
#undef my_m_MT_R_2che1pawn_B_1che2ma  
#undef my_m_MT_R_2che1pawn_B_1che1pao1pawn  
#undef my_m_MT_R_2che1pawn_B_1che1ma1pawn  
#undef my_m_MT_R_2che1pawn_B_1che2pawn  
#undef my_m_MT_R_1che2pao_B_1che1pao1ma   
#undef my_m_MT_R_1che2pao_B_1che1pao1pawn 
#undef my_m_MT_R_1che1pao1pawn_B_1che1ma1pawn  
#undef my_m_MT_R_1che1pao1ma_B_1che1ma1pawn   
#undef my_m_MT_R_1che1pao1ma_B_1che1pao1pawn   
#undef my_m_MT_R_1che2ma_B_1che1pao1pawn    
#undef my_m_MT_R_1che1pao1pawn_B_1che2pawn  
#undef my_m_MT_R_1che1pao1pawn_B_2pao1ma  
#undef my_m_MT_R_1che1pao1pawn_B_1pao2ma 
#undef my_m_MT_R_1che1pao1pawn_B_2pao1pawn 
#undef my_m_MT_R_1che1pao1pawn_B_1pao1ma1pawn  
#undef my_m_MT_R_1che1pao1pawn_B_2ma1pawn  
#undef my_m_MT_R_1che1pao1pawn_B_1pao2pawn  
#undef my_m_MT_R_1che1pao1pawn_B_1ma2pawn  
#undef my_m_MT_R_1che1pao1pawn_B_3pawn  
#undef my_m_MT_R_1che1ma1pawn_B_1che2pawn  
#undef my_m_MT_R_1che1ma1pawn_B_2pao1ma  
#undef my_m_MT_R_1che1ma1pawn_B_1pao2ma  
#undef my_m_MT_R_1che1ma1pawn_B_2pao1pawn  
#undef my_m_MT_R_1che1ma1pawn_B_1pao1ma1pawn  
#undef my_m_MT_R_1che1ma1pawn_B_2ma1pawn  
#undef my_m_MT_R_1che1ma1pawn_B_1pao2pawn  
#undef my_m_MT_R_1che1ma1pawn_B_1ma2pawn 
#undef my_m_MT_R_1che1ma1pawn_B_3pawn  
#undef my_m_MT_R_1che2pawn_B_2pao1ma 
#undef my_m_MT_R_1che2pawn_B_1pao2ma 
#undef my_m_MT_R_1che2pawn_B_2pao1pawn  
#undef my_m_MT_R_1che2pawn_B_1pao1ma1pawn  
#undef my_m_MT_R_1che2pawn_B_2ma1pawn  
#undef my_m_MT_R_1che2pawn_B_1pao2pawn 
#undef my_m_MT_R_1che2pawn_B_1ma2pawn  
#undef my_m_MT_R_1che2pawn_B_3pawn  
#undef my_m_MT_R_2pao1ma_B_2pao1pawn
#undef my_m_MT_R_2pao1ma_B_1pao2ma  
#undef my_m_MT_R_1pao2ma_B_2pao1pawn  
#undef my_m_MT_R_2pao1ma_B_1pao1ma1pawn  
#undef my_m_MT_R_1pao2ma_B_1pao1ma1pawn  
#undef my_m_MT_R_2pao1ma_B_2ma1pawn  
#undef my_m_MT_R_1pao2ma_B_2ma1pawn  
//#undef m_MT_2pao1pawn_2pao1pawn  
#undef my_m_MT_R_2pao1pawn_B_1pao2pawn  
#undef my_m_MT_R_2pao1pawn_B_1ma2pawn  
#undef my_m_MT_R_2pao1pawn_B_1pao1ma1pawn  
#undef my_m_MT_R_2pao1pawn_B_2ma1pawn  
//#undef m_MT_1pao1ma1pawn_1pao1ma1pawn  
#undef my_m_MT_R_1pao1ma1pawn_B_2ma1pawn  
#undef my_m_MT_R_1pao1ma1pawn_B_1pao2pawn  
#undef my_m_MT_R_1pao1ma1pawn_B_1ma2pawn  
#undef my_m_MT_R_2ma1pawn_B_1pao2pawn 
#undef my_m_MT_R_2ma1pawn_B_1ma2pawn  
//#undef m_MT_BR_1pao2pawn  
#undef my_m_MT_R_1pao2pawn_B_1ma2pawn  
#undef my_m_MT_R_1pao2pawn_B_3pawn    
#undef m_MT_B_1pao2pawn_R_3pawn  
//#undef m_MT_1ma2pawn_1ma2pawn 
#undef my_m_MT_R_1ma2pawn_B_3pawn    
//#undef m_MT_3pawn_TO_3pawn  

